// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYJD-vLygLIqJq37clLrKVLABOSHbftNg',
    appId: '1:997829664351:web:2f0b2bad7668c4e3f945ea',
    messagingSenderId: '997829664351',
    projectId: 'test-eb0a8',
    authDomain: 'test-eb0a8.firebaseapp.com',
    databaseURL: 'https://test-eb0a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-eb0a8.firebasestorage.app',
    measurementId: 'G-2XW70GNTBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfnnWKevCxN936uIVA3b2HaAUP0_MlHjI',
    appId: '1:997829664351:android:bb0ab3a61fcd9a45f945ea',
    messagingSenderId: '997829664351',
    projectId: 'test-eb0a8',
    databaseURL: 'https://test-eb0a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-eb0a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDREZ6g9p11n2wNwd5FpxJSvtp2zZdheTI',
    appId: '1:997829664351:ios:4abdfaa239debbecf945ea',
    messagingSenderId: '997829664351',
    projectId: 'test-eb0a8',
    databaseURL: 'https://test-eb0a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-eb0a8.firebasestorage.app',
    androidClientId: '997829664351-7fq7j88i1dep06f32l4e660o9idkpinu.apps.googleusercontent.com',
    iosClientId: '997829664351-157lg5atkjmmkd77gh6erlnjbl88vjbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFintrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDREZ6g9p11n2wNwd5FpxJSvtp2zZdheTI',
    appId: '1:997829664351:ios:4abdfaa239debbecf945ea',
    messagingSenderId: '997829664351',
    projectId: 'test-eb0a8',
    databaseURL: 'https://test-eb0a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-eb0a8.firebasestorage.app',
    androidClientId: '997829664351-7fq7j88i1dep06f32l4e660o9idkpinu.apps.googleusercontent.com',
    iosClientId: '997829664351-157lg5atkjmmkd77gh6erlnjbl88vjbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFintrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYJD-vLygLIqJq37clLrKVLABOSHbftNg',
    appId: '1:997829664351:web:9b4e3e54e86b2163f945ea',
    messagingSenderId: '997829664351',
    projectId: 'test-eb0a8',
    authDomain: 'test-eb0a8.firebaseapp.com',
    databaseURL: 'https://test-eb0a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-eb0a8.firebasestorage.app',
    measurementId: 'G-M907QGL8L3',
  );

}